### ISSUE TITLE
Configuration international taxes

### ISSUE THREAD

**Issue by grosykevin** [yireo/Magento_EU_Tax_Rates#4]
Hello, I'm looking for VAT for international rates. Is this file correct?
What my client sells it's hair extensions

**Comment by jissereitsma** [comment]
Hi, this project is indeed about VAT for EU rates. If you sell within the EU, EU VAT applies. If you sell from within the EU to outside the EU, no VAT applies. But do not trust me for this - ask your bookkeeper to confirm this. As for hair extensions, I'm really not able to answer to which tax group hair extensions belong. See the links on our project page - they will lead you to sites that need to be researched by you to find out which rate applies how.

**Comment by pierre93** [comment]
In conclusion for the other countries he did not need VAT there?

**Comment by jissereitsma** [comment]
As far as I understand EU VAT regulations. But I'm not a bookkeeper, and this project is actually not meant as a guideline for bookkeeping either. The project simply makes it easier to import certain tax-rates into Magento. How those tax-rates should be applied to which products under which circumstances is something I would rather ask a qualified person (a bookkeeper or a tax agency).
