### ISSUE TITLE
Greece 6.5% rate drops to 6% as of July 1st 2015

### ISSUE THREAD

**Issue by hostep** [yireo/Magento_EU_Tax_Rates#6]
According to these articles:
http://www.vatlive.com/european-news/greece-new-vat-rises-in-creditor-talks/
http://www.vatlive.com/european-news/greek-vat-rises-in-confusion/

Not sure if this is already accepted or not, but I guess so, since it says so on:
http://www.vatlive.com/vat-rates/european-vat-rates/eu-vat-rates/

**Comment by yireo** [comment]
Thanks for watching for it. Personally I felt it also important to see whether a grexit() would happen or not - no, just kidding ;) I'll change the listing and go through the vatlive.com site for other changes. It's one of the resources I decided to take as authoritive, so don't shoot the messenger.
